name: col864_proj
channels:
  - pytorch
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=5_kmp_llvm
  - anywidget=0.9.18=pyhd8ed1ab_0
  - aom=3.7.1=h59595ed_0
  - blas=1.0=mkl
  - brotlicffi=1.0.9.2=py310h6a678d5_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py310h4eded50_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - comm=0.2.3=pyhe01879c_0
  - cuda-version=11.8=h70ddcb2_3
  - cudatoolkit=11.8.0=h4ba93d1_13
  - cudnn=8.9.7.29=hbc23b4c_3
  - dav1d=1.2.1=h5eee18b_0
  - deepdiff=8.6.1=pyhcf101f3_0
  - expat=2.7.1=h6a678d5_0
  - farama-notifications=0.0.4=pyhd8ed1ab_0
  - ffmpeg=6.1.1=gpl_hf3b701a_101
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h2c49b7f_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.16=hb03c661_0
  - giflib=5.2.2=h5eee18b_0
  - gmp=6.3.0=hac33072_2
  - gnutls=3.7.9=hb077bed_0
  - graphite2=1.3.14=h295c915_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.2=h59595ed_0
  - intel-openmp=2023.0.0=h9e868ea_25371
  - ipywidgets=8.1.7=pyhd8ed1ab_0
  - jax-jumpy=1.0.0=pyhd8ed1ab_1
  - jpeg=9f=h5ce9db8_0
  - jupyter-ui-poll=1.0.0=pyhd8ed1ab_1
  - jupyterlab_widgets=3.0.15=pyhd8ed1ab_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.44=h153f514_2
  - leptonica=1.82.0=hfdeec58_3
  - lerc=4.0.0=h6a678d5_0
  - libarchive=3.8.2=h3ec8f01_0
  - libass=0.17.1=h39113c1_2
  - libblas=3.9.0=16_linux64_mkl
  - libcblas=3.9.0=16_linux64_mkl
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.125=hb03c661_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libglib=2.84.4=h77a78f3_0
  - libgomp=15.2.0=h767d61c_7
  - libiconv=1.18=h3b78370_2
  - libidn2=2.3.8=hfac485b_1
  - liblapack=3.9.0=16_linux64_mkl
  - libnsl=2.0.0=h5eee18b_0
  - libogg=1.3.5=h27cfd23_1
  - libopenjpeg=2.5.4=hee96239_0
  - libopenvino=2023.2.0=h59595ed_0
  - libopenvino-auto-batch-plugin=2023.2.0=h59595ed_0
  - libopenvino-auto-plugin=2023.2.0=h59595ed_0
  - libopenvino-hetero-plugin=2023.2.0=h59595ed_0
  - libopenvino-intel-cpu-plugin=2023.2.0=h59595ed_0
  - libopenvino-intel-gpu-plugin=2023.2.0=h59595ed_0
  - libopenvino-ir-frontend=2023.2.0=h59595ed_0
  - libopenvino-onnx-frontend=2023.2.0=h59595ed_0
  - libopenvino-paddle-frontend=2023.2.0=h59595ed_0
  - libopenvino-pytorch-frontend=2023.2.0=h59595ed_0
  - libopenvino-tensorflow-frontend=2023.2.0=h59595ed_0
  - libopenvino-tensorflow-lite-frontend=2023.2.0=h59595ed_0
  - libopus=1.3.1=h5eee18b_1
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h2ed474d_0
  - libprotobuf=3.21.12=hfc55251_2
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libtasn1=4.20.0=hb03c661_1
  - libtheora=1.2.0=h32ad74f_1
  - libtiff=4.7.0=hde9077f_0
  - libunistring=0.9.10=h7f98852_0
  - libuuid=1.41.5=h5eee18b_0
  - libva=2.21.0=h4ab18f5_2
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.13.1=h6a678d5_0
  - libwebp=1.3.2=h9f374a3_1
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h0b41bf4_0
  - libxml2=2.13.8=hfdd30dd_0
  - libzlib=1.3.1=hb25bd0a_0
  - llvm-openmp=20.1.8=h4922eb0_0
  - lz4-c=1.9.4=h6a678d5_1
  - magma=2.6.2=hc72dce7_0
  - mkl=2022.2.1=h6508926_16999
  - mkl-service=2.4.0=py310h9263142_0
  - mkl_fft=1.3.8=py310h88d2f6f_0
  - mkl_random=1.2.4=py310h378cecd_2
  - nccl=2.27.3.1=h03a54cd_0
  - ncurses=6.5=h7934f7d_0
  - nettle=3.9.1=h7ab15ed_0
  - ninja=1.13.1=h171cf75_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - ocl-icd-system=1.0.0=1
  - opencl-headers=2025.06.13=h5888daf_0
  - openh264=2.4.0=h59595ed_0
  - openjpeg=2.5.4=h4e0627c_0
  - openssl=3.5.4=h26f9b46_0
  - p11-kit=0.24.1=hc5aa10d_0
  - pcre2=10.46=hf426167_0
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h7934f7d_0
  - psygnal=0.14.2=pyhd8ed1ab_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pugixml=1.14=h59595ed_0
  - pycparser=2.23=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.18=h1a3bd86_0
  - python_abi=3.10=2_cp310
  - pytorch-mutex=1.0=cpu
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=py310h06a4308_0
  - rerun-sdk=0.26.2=py310h7f0bd4e_0
  - setuptools=80.9.0=py310h06a4308_0
  - sleef=3.9.0=ha0421bc_0
  - snappy=1.1.10=hdb0a2a9_1
  - sqlite=3.50.2=hb25bd0a_1
  - svt-av1=1.8.0=h59595ed_0
  - tbb=2021.8.0=hdb19cb5_0
  - tesseract=5.2.0=hb0d2e87_3
  - tk=8.6.14=h39e8969_0
  - typing_extensions=4.15.0=py310h06a4308_0
  - urllib3=2.5.0=py310h06a4308_0
  - wheel=0.45.1=py310h06a4308_0
  - widgetsnbextension=4.0.14=pyhd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xorgproto=2024.1=hb9d3cd8_1
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.11.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.1
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - asciitree==0.3.3
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - av==15.1.0
      - beautifulsoup4==4.14.2
      - catkin-pkg==1.1.0
      - chardet==5.2.0
      - charset-normalizer==3.4.4
      - click==8.3.0
      - cmake==4.1.2
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==4.1.1
      - decorator==5.2.1
      - detr==0.0.1
      - diffusers==0.35.2
      - dill==0.4.0
      - distro==1.9.0
      - dm-control==1.0.34
      - dm-env==1.6
      - dm-tree==0.1.9
      - docutils==0.22.2
      - draccus==0.10.0
      - einops==0.8.1
      - etils==1.13.0
      - evdev==1.9.2
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fasteners==0.20
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - glfw==2.10.0
      - gym-aloha==0.1.3
      - gym-notices==0.1.0
      - gymnasium==1.2.2
      - h11==0.16.0
      - h5py==3.15.1
      - hf-transfer==0.1.9
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.35.3
      - hydra-core==1.2.0
      - idna==3.11
      - imageio==2.22.0
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - inquirerpy==0.3.4
      - ipython==8.37.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jsonlines==4.0.0
      - kiwisolver==1.4.9
      - labmaze==1.0.6
      - lerobot==0.4.0
      - lxml==6.0.2
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - mediapy==1.2.4
      - mergedeep==1.3.4
      - mujoco==3.3.7
      - multidict==6.7.0
      - multiprocess==0.70.16
      - mypy-extensions==1.1.0
      - numcodecs==0.13.1
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - omegaconf==2.3.0
      - opencv-python-headless==4.12.0.88
      - orderly-set==5.5.0
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - pexpect==4.9.0
      - pfzy==0.3.4
      - pillow==12.0.0
      - platformdirs==4.5.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==6.33.0
      - psutil==7.1.2
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==22.0.0
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pygame==2.1.2
      - pygments==2.19.2
      - pymunk==6.2.1
      - pynput==1.8.1
      - pyopengl==3.1.10
      - pyparsing==3.2.5
      - pyquaternion==0.9.9
      - pyserial==3.5
      - python-dateutil==2.9.0.post0
      - python-xlib==0.33
      - pytz==2025.2
      - pywavelets==1.8.0
      - pyyaml==6.0.3
      - pyyaml-include==1.4.1
      - regex==2025.10.23
      - rerun-notebook==0.26.2
      - rospkg==1.6.0
      - safetensors==0.6.2
      - scikit-image==0.19.3
      - scipy==1.15.3
      - sentry-sdk==2.42.1
      - shapely==1.8.4
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - stack-data==0.6.3
      - sympy==1.14.0
      - termcolor==3.2.0
      - tifffile==2025.5.10
      - toml==0.10.2
      - torch==2.7.1
      - torchcodec==0.5
      - torchvision==0.22.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triton==3.3.1
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - vq-bet==0.1.0
      - wandb==0.21.4
      - wcwidth==0.2.14
      - wrapt==2.0.0
      - xxhash==3.6.0
      - yarl==1.22.0
      - zarr==2.18.3
      - zipp==3.23.0
prefix: /home/ghost404/miniconda3/envs/col864_proj
