
save_path: /home/dhruv/VQ-BET-ALOHA-Insertion/vq_bet_runs

wandb_entity: dhruv-101-iit-delhi

dataset_path: /home/dhruv/VQ-BET-ALOHA-Insertion/vq_bet_datasets_local 

datasets:
    aloha_insertion_dataset:  lerobot/aloha_sim_insertion_human
